print("First 10 letters in lower case:")
t = head(letters, 10)
print(t)
print("Last 10 letters in upper case:")
b= tail(LETTERS, 10)
print(b)
print("Letters between 22nd to 24th letters in upper case:")
e = head(letters[22:24])
print(e)